### PR TITLE
Add unit tests for CountryCell and CountryPickerView

### PR DESCRIPTION
**Pull request by SURYAKANTSHARMA**
- Made test coverage 92% yeess big achievement  current coverage is 12% please review it !!.
- Refactor for better code 

Screenshot 2021-01-09 at 4 02 03 PM

### CODE REVIEW

**Comment by SURYAKANTSHARMA** [comment]
@Sharkesm @hardeep-singh need you guys help to review and test one time before get this merge

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA Current project warnings 
image

**Comment by SURYAKANTSHARMA** [comment]
Hmm it is working for me

**Comment by SURYAKANTSHARMA** [comment]
> @SURYAKANTSHARMA Current project warnings 
> image
> 

Try build clean.

**Comment by Sharkesm** [comment]
> > @SURYAKANTSHARMA Current project warnings
> > image
> 
> Try build clean.

Yeah, still experiencing the same issue. It's something to do with the Swift packaging if I'm not mistaken.

**Review by Sharkesm — APPROVED** [review]

**Comment by Sharkesm** [comment]
LGTM 🌟

**Pull request merged**
