### PR TITLE
Add favourite

### PR DESCRIPTION
**Pull request by SURYAKANTSHARMA**
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-18 at 12 58 15
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-18 at 12 58 36
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-18 at 13 02 29
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-18 at 13 02 41
Add enhancement #53

### CODE REVIEW

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA Reviewing it on the weekend :)

**Comment by SURYAKANTSHARMA** [comment]
> @SURYAKANTSHARMA Reviewing it on the weekend :)

2 PRs are waiting

**Review by Sharkesm — CHANGES_REQUESTED** [review]
@SURYAKANTSHARMA  **Minor issue:** The country section on the right side is not sorted properly not sure if that's the case with the favorite feature and overall everything else looks good.

**Comment by SURYAKANTSHARMA** [comment]
It only in case of favourite feature.will check thanks

**Comment by SURYAKANTSHARMA** [comment]
> @SURYAKANTSHARMA **Minor issue:** The country section on the right side is not sorted properly not sure if that's the case with the favorite feature and overall everything else looks good.
> 
> 

fix @Sharkesm

**Review by Sharkesm — APPROVED** [review]
LGTM 🔥

**Pull request merged**
