### PR TITLE
add Kosovo country

### PR DESCRIPTION
**Pull request by musa-almatri**
- This pull requests has three commits:

- compress flag icons without losing the quality of the images.
- add Kosovo country
- remove the search bar placeholder text "Search country name here.." ; to use the default placeholder because:
1- It is already localized by the system.
2- "Search" placeholder is enough. it is clear that this is a country search page.

### CODE REVIEW

**Comment by Sharkesm** [comment]
@musa-almatri Please review the fail **test** on travis and confirm all test results are positive. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by musa-almatri** [comment]
Done

**Comment by Sharkesm** [comment]
>Done

@musa-almatri Noted 🚀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SURYAKANTSHARMA** [comment]
LGTM

**Pull request merged**
