### PR TITLE
I os15 and above

### LINKED ISSUE #118: How to access SwiftUI views using Swift Package Manager?
Using SPM (CountryPicker 3.0.0) I do not see any of the SwiftUI files contained in CountryPicker/CountryPickeriOS15+

**To Reproduce**
Add CountryPicker to Xcode via Swift Package Manager:
Screenshot 2024-04-16 at 10 37 59

The folder CountryPicker/CountryPickeriOS15+/CountryPickerSPM is not present in the dependency and I can't access any of the SwiftUI views that exist in the github project:
Screenshot 2024-04-16 at 10 38 17

**Expected behavior**
I should be able to access the SwiftUI files in CountryPicker/CountryPickeriOS15+/CountryPickerSPM for example CountryPickerView

### PR DESCRIPTION
**Pull request by SURYAKANTSHARMA**
PR
- Remove old support uikit from next version
- fix #118 
- base version iOS 15+ 
- Next expected version 4.0.0

### CODE REVIEW

**Comment by SURYAKANTSHARMA** [comment]
#118

**Comment by SURYAKANTSHARMA** [comment]
Build is failing because .yml project location is changed.

**Comment by SURYAKANTSHARMA** [comment]
Merging PR Please feel free to comment in case you review code and face some issue @Sharkesm

**Comment by Sharkesm** [comment]
LGTM mate and great work 🍒

**Pull request merged**
