### PR TITLE
Enhancement/readme

### PR DESCRIPTION
**Pull request by Hesham96**
Update README , the countryImage is always hidden till I remove this line "countryImage.IsHidden = true " from ViewDidLoad() {iPhone 11}

### CODE REVIEW

**Comment by Hesham96** [comment]
> Good catch 💯
> 
> Other:
> 
> * Since by default there's no `UIImage` loaded into the `UIImageView`, I reckon to remove the rest of `countryImageView.isHidden` considering that `UIImageView` is always available.

Thanks for your reply,
In my case, I already put the App default country image "Egypt" and let it visible and when user select another country code/image it overrides the default one.

**Comment by Sharkesm** [comment]
@Hesham96 Can you include those changes as well

**Comment by SURYAKANTSHARMA** [comment]
@Hesham96  any update ?

**Comment by SURYAKANTSHARMA** [comment]
@Sharkesm  bro should I merge this or close ?  as @Hesham96 don't reply.

**Comment by Sharkesm** [comment]
@SuryaKantSh We close it. Since it's not a crucial fault on the development side.

**Pull request closed without merging**
